"""Generate the runtime device-command allowlist from bundled Vulkan headers."""
from pathlib import Path
import re
root = Path(__file__).resolve().parents[1]
commands = set()
for header in (root / "third-party/vulkan-headers/include/vulkan").glob("*.h"):
    commands.update(re.findall(r"\*PFN_(vk\w+)\)\(\s*(?:VkDevice|VkQueue|VkCommandBuffer)\s+", header.read_text()))
assert "vkCreateImage" in commands and "vkEnumeratePhysicalDevices" not in commands
output = root / "src/openxr/RuntimeDeviceCommands.inc"
output.write_text("// Generated by tools/generate_runtime_device_commands.py; do not edit.\n" +
                  "".join('    "' + name + '",\n' for name in sorted(commands)))
print(f"Generated {len(commands)} device commands")
